Adjust ascension detection to work in compact character pane
loathers/libram pull request #396
Opened 2022-11-05 16:09 UTC by ajcoppa

The existing ascension detection code looks for "Astral Spirit" in the character pane, but when using KoL's built in "compact character pane" option, the class name is never shown:

<img width="147" alt="Screen Shot 2022-11-05 at 12 05 39 PM" src="https://user-images.githubusercontent.com/481668/200129117-dc7e5a67-3e4f-4d82-b1b7-9ea9dc7323b6.png">

Instead, can we use this detection that checks whether Lvl. is followed by an image? I avoided coding in the actual image name in case KoL ever changes that for some reason.

Manually tested the ASH versions of these directly in the mafia CLI:
```
> ash contains_text(visit_url("charpane.php"), "Lvl. <img src=")

Returned: true
```

Also added a more specific error string so it's clear what failure is happening if users encounter this in the future.

2022-11-05 16:12 UTC, ajcoppa commented
Amusingly, while in Valhalla, you can't change your KoL options so I didn't have a way to manually test if this works correctly for the full character pane. It would be awesome if someone can confirm this text will work there too.

2022-11-06 13:25 UTC, ajcoppa commented
After some Discord feedback I tried using api.php to check the class in a more direct way, but unfortunately api.php doesn't work while in Valhalla and gets force-redirected to afterlife.php . Adjusted the string to just search for "Karma:" in the char pane instead – ready for review.

2022-11-07 06:12 UTC, s-k-z requested changes

2022-11-07 06:12 UTC, s-k-z commented on src/ascend.ts
> +      "Couldn't determine whether ascension completed successfully"
I wouldn't insert a new message here, the default is an important reminder.

2022-11-07 20:16 UTC, s-k-z approved these changes

2022-11-07 20:19 UTC, merged